from base import DocType

class ERPNextDocType(DocType):
    CUSTOMER            = "Customer"
    SUPPLIER            = "Supplier"
    ADDRESS             = "Address"
    BANK_ACCOUNT        = "Bank Account"
    BANK                = "Bank"
    CONTACT             = "Contact"
    SALES_INVOICE       = "Sales Invoice"
    PURCHASE_INVOICE    = "Purchase Invoice"
    SALES_ORDER         = "Sales Order"
    PURCHASE_ORDER      = "Purchase Order"
    QUOTATION           = "Quotation"
    PAYMENT_ENTRY       = "Payment Entry"
    ITEM                = "Item"
    PRICE_LIST          = "Price List"
    ITEM_PRICE          = "Item Price"
    ITEM_GROUP          = "Item Group"
    CUSTOM_FIELD        = "Custom Field"
    MANUFACTURER        = "Manufacturer"
    PROPERTY_SETTER     = "Property Setter"
    ACCOUNT             = "Account"
    WAREHOUSE           = "Warehouse"
    STOCK_ENTRY         = "Stock Entry"
    DELIVERY_NOTE       = "Delivery Note"
    JOURNAL_ENTRY       = "Journal Entry"
    COMMUNICATION       = "Communication"
    FISCAL_YEAR         = "Fiscal Year"
    PAYMENT_TERMS_TEMPLATE = "Payment Terms Template"